### ISSUE TITLE
region-file

### ISSUE THREAD

**Issue by swvanderlaan** [KChen-lab/Monopogen#41]
I want to process the whole genome. How does `Monopogen` that the X, Y, XY/PAR1/PAR2, MT chromosome (regions) are noted? I now (naively) have this:

```
chr1
chr2
chr3
chr4
chr5
chr6
chr7
chr8
chr9
chr10
chr11
chr12
chr13
chr14
chr15
chr16
chr17
chr18
chr19
chr20
chr12
chr22
chrX
chrXY
chrY
chrMT
```

**Comment by jinzhuangdou** [comment]
Hi, Monopogen does not work on MT/sex chromosomes since we do not prepare for the imputation panel for them. You can set region.lst as  (with -t set as 22 for multi-threading function)
chr1
chr2
chr3
chr4
chr5
chr6
chr7
chr8
chr9
chr10
chr11
chr12
chr13
chr14
chr15
chr16
chr17
chr18
chr19
chr20
chr12
chr22

**Comment by swvanderlaan** [comment]
Superb. Thanks
